core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', log_in, name='log_in'),
    path('logo_out/', log_out, name='log_out'),
    path('profile/', profile, name='profile'),
    path('prof_image/', prof_image, name='prof_image'),
    path('staff_panel/', staff_panel, name='staff_panel'),
    path('user_crud/',user_crud,name='user_crud'),
    path('delete_user/<int:id>',delete_user,name='delete_user'),
    path('exam_crud/',exam_crud,name='exam_crud'),
    path('delete_exam/<int:id>',delete_exam,name='delete_exam'),
    path('export_data/', file_load_view, name='export_data'),
    path('publish_questions/',publish_questions,name='publish_questions'),



]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core'))
]
if settings.DEBUG==True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.core.exceptions import ValidationError

the_class = (
    ('حضانه', 'حضانه'),
    ('الصف الاول', 'الصف الاول'),
    ('الصف الثانى', 'الصف الثانى'),
    ('الصف الثالث', 'الصف الثالث'),
    ('الصف الرابع', 'الصف الرابع'),
    ('الصف الخامس', 'الصف الخامس'),
    ('الصف السادس', 'الصف السادس'),
    ('خدام', 'خدام'),

)


# def validate_date(date):
#     if date > timezone.now().date():
#         raise ValidationError("Date cannot be in the future")
#

def image_upload(instance, filename):
    imagename, extension = filename.split(".")
    return "core/%s.%s" % (instance.user, extension)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile/', null=True, blank=True)
    p_class = models.CharField(max_length=50, choices=the_class)
    score = models.IntegerField(default=0)
    last_update = models.DateTimeField(auto_now_add=timezone.now(), null=True, blank=True)

    def __str__(self):
        return self.user.username

    def get_student_score(self):
        prof = Profile.objects.get(user=self.user)
        res = Results.objects.filter(profile=prof, is_correct=True)
        if res.exists():
            return res.count()
        else:
            return 0

    # def get_score(self):
    #     dd = Profile.objects.filter()
    #     for p in dd:
    #         p['score'] = self.get_student_score
    #         dd.save()
    #     return dd


@receiver(post_save, sender=User)
def create_profile(sender, created, instance, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class Results(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    question_ans = models.CharField(max_length=100)
    student_ans = models.CharField(max_length=100, null=True, blank=True)
    correct_ans = models.CharField(max_length=100)
    is_correct = models.BooleanField()

    def __str__(self):
        return str(self.profile)


z_class = (
    ('حضانه', 'حضانه'),
    ('الصف الاول', 'الصف الاول'),
    ('الصف الثانى', 'الصف الثانى'),
    ('الصف الثالث', 'الصف الثالث'),
    ('الصف الرابع', 'الصف الرابع'),
    ('الصف الخامس', 'الصف الخامس'),
    ('الصف السادس', 'الصف السادس'),
    ('خدام', 'خدام'),

)


class Exam(models.Model):
    t_class = models.CharField(max_length=50, choices=z_class)
    question = models.CharField(max_length=100)
    answer1 = models.CharField(max_length=100)
    answer2 = models.CharField(max_length=100)
    answer3 = models.CharField(max_length=100)
    answer4 = models.CharField(max_length=100)
    correct_answer = models.CharField(max_length=100)
    last_update = models.DateTimeField(auto_now_add=timezone.now(), null=True, blank=True)
    is_published = models.BooleanField()

    def __str__(self):
        return self.question

core/forms.py
from django import forms
from .models import *


class Exam_form(forms.Form):
    question = forms.CharField(widget=forms.TextInput(attrs={
        "name": "question",
        "class": "form-control",
        "id": "question",
        "placeholder": "السؤال",

    }))
    answer1 = forms.CharField(widget=forms.TextInput(attrs={
        "name": "answer1",
        "class": "form-control",
        "id": "answer1",
        "placeholder": "الاختيار الاول",

    }))
    answer2 = forms.CharField(widget=forms.TextInput(attrs={
        "name": "answer2",
        "class": "form-control",
        "id": "answer2",
        "placeholder": "الاختيار الثانى",

    }))
    answer3 = forms.CharField(widget=forms.TextInput(attrs={
        "name": "answer3",
        "class": "form-control",
        "id": "answer3",
        "placeholder": "الاختيار الثالث",

    }))
    answer4 = forms.CharField(widget=forms.TextInput(attrs={
        "name": "answer4",
        "class": "form-control",
        "id": "answer4",
        "placeholder": "الاختيار الرابع",

    }))
    correct_answer = forms.CharField(widget=forms.TextInput(attrs={
        "name": "correct_answer",
        "class": "form-control",
        "id": "correct_answer",
        "placeholder": "الاجابه الصحيحه",

    }))


class prof_image_form(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.contrib.admin.views.decorators import staff_member_required
# import csv
from django.http import HttpResponse
import xlwt


# import unicodecsv

def log_in(request):
    if request.method == 'POST':
        u = request.POST['username']
        p = request.POST['password']
        re = auth.authenticate(username=u, password=p)
        if re is not None:
            auth.login(request, re)
            if request.user.is_staff:
                return redirect('core:staff_panel')
            return redirect('core:profile')
        else:
            messages.warning(request, 'اسم المستخدم او الرقم السرى غير صحيح')
            return redirect('/')
    else:
        return render(request, 'login.html', {})


@login_required(login_url='/')
def log_out(request):
    auth.logout(request)
    return redirect('/')


@login_required(login_url='/')
def profile(request):
    if request.user.is_staff:
        return redirect('core:staff_panel')
    else:
        prof = Profile.objects.get(user=request.user)
        profs = Profile.objects.filter(p_class=prof.p_class).exclude(user__is_staff=True).exclude(score=0).order_by(
            '-score')[0:10]
        exam = Exam.objects.filter(t_class=prof.p_class)
        if request.method == 'POST':
            for m in exam:
                # if request.POST.get(m.question, )=="":
                #  messages.info(request,"من فضلك قم بالاجابه على جميع الاسئله")
                #  return redirect('core:profile')
                print(request.POST.get(m.question, ))
                if request.POST.get(m.question, ) == m.correct_answer:
                    results = Results.objects.create(
                        profile=prof,
                        question_ans=m.question,
                        student_ans=request.POST.get(m.question, ),
                        correct_ans=m.correct_answer,
                        is_correct=True,
                    )
                    results.save()
                    prof.score += 10
                    prof.save()
                elif request.POST.get(m.question, ) != m.correct_answer:
                    if request.POST.get(m.question, ) == None:
                        prof.save()
                    else:
                        results = Results.objects.create(
                            profile=prof,
                            question_ans=m.question,
                            student_ans=request.POST.get(m.question, ),
                            correct_ans=m.correct_answer,
                            is_correct=False,
                        )

            return redirect('core:profile')

        else:
            results = Results.objects.filter(profile=prof)
            # for quest in exam:
            #     for res in results:
            #
        form = prof_image_form()
        exam = Exam.objects.filter(t_class=prof.p_class, is_published=True).exclude(
            question__in=results.values_list('question_ans', flat=True))

        return render(request, 'profile.html', {'prof': prof, 'exam': exam, 'profs': profs, 'form': form})


@login_required(login_url='/')
def prof_image(request):
    prof = Profile.objects.get(user=request.user)
    form = prof_image_form(request.POST, request.FILES, instance=prof)
    if form.is_valid():
        form.save()

    return redirect('core:profile')


@staff_member_required(login_url='/')
def staff_panel(request):
    return render(request, 'staff_panel.html', {})


@staff_member_required(login_url='/')
def user_crud(request):
    p = Profile.objects.get(user=request.user)
    profile = Profile.objects.filter(p_class=p.p_class).exclude(user__is_staff=True).order_by('-last_update')
    if request.method == 'POST':
        u = request.POST['username']
        p1 = request.POST['password1']
        p2 = request.POST['password2']
        if User.objects.filter(username=u).exists():
            messages.info(request, 'تاكد من عدم تكرار اسم المستخدم')
            return redirect('core:user_crud')
        elif u == "":
            messages.info(request, 'من فضلك قم باضافة اسم للمستخدم')
            return redirect('core:user_crud')
        elif p1 != p2:
            messages.info(request, 'تاكد من ان الرقم السري وتاكيد الرقم السري متطابقين ')
            return redirect('core:user_crud')
        elif len(p1) < 8:
            messages.info(request, 'عفوا الرقم السري يجب ان لايقل عن 8 عناصر  ')
            return redirect('core:user_crud')
        else:
            user = User.objects.create_user(username=u, password=p1)
            user.save()
            k = Profile.objects.get(user=user)
            k.p_class = p.p_class
            k.save()

            return redirect('core:user_crud')
    else:
        return render(request, 'user_crud.html', {'prof': profile})


@staff_member_required(login_url='/')
def delete_user(request, id):
    user = User.objects.get(id=id)
    user.delete()
    return redirect('core:user_crud')


@staff_member_required(login_url='/')
def file_load_view(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="student.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Student')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['اسم المستخدم', 'الدرجات', ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    p = Profile.objects.get(user=request.user)
    rows = Profile.objects.filter(p_class=p.p_class).exclude(user__is_staff=True).order_by(
        '-last_update').values_list('user__username', 'score')
    # rows = StudentForm.objects.all().values_list('firstname', 'lastname', 'email')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response


# def file_load_view(request):
#     p = Profile.objects.get(user=request.user)
#     p1 = Profile.objects.filter(p_class=p.p_class).exclude(user__is_staff=True).order_by(
#         '-last_update').values_list('user__username', flat=True)
#     p2 = Profile.objects.filter(p_class=p.p_class).exclude(user__is_staff=True).order_by(
#         '-last_update').values_list('score', flat=True)
#     # Create the HttpResponse object with the appropriate CSV header.
#     response = HttpResponse(content_type='text/csv')
#     response['Content-Disposition'] = 'attachment; filename="students_name.csv"'
#
#     # writer = unicodecsv.writer(response, encoding='utf-16"')
#     writer = csv.writer(response)
#
#     writer.writerow(['username', 'score'])
#     rows = zip(p1, p2)
#     for m in rows:
#         writer.writerow(m)
#
#     return response


@staff_member_required(login_url='/')
def exam_crud(request):
    p = Profile.objects.get(user=request.user)
    exam = Exam.objects.filter(t_class=p.p_class).order_by('-last_update')
    if request.method == 'POST':
        form = Exam_form(request.POST)
        if form.is_valid():
            exam_form = Exam.objects.create(
                t_class=p.p_class,
                question=form.cleaned_data['question'],
                answer1=form.cleaned_data['answer1'],
                answer2=form.cleaned_data['answer2'],
                answer3=form.cleaned_data['answer3'],
                answer4=form.cleaned_data['answer4'],
                correct_answer=form.cleaned_data['correct_answer'],
                is_published=False,
            )
            exam_form.save()
            # myform = form.save(commit=False)
            # myform.t_class = p.p_class
            # myform.save()
            return redirect('core:exam_crud')
        else:
            messages.info(request, 'من فضلك تاكد من مليء جميع الحقول')
            return redirect('core:exam_crud')
    else:
        exam_form = Exam_form()
        return render(request, 'exam_crud.html', {'exam_form': exam_form, 'exam': exam})


@staff_member_required(login_url='/')
def publish_questions(request):
    p = Profile.objects.get(user=request.user)
    exam = Exam.objects.filter(t_class=p.p_class, is_published=False).order_by('-last_update')
    for m in exam:
        m.is_published = True
        m.save()
    return redirect('core:exam_crud')


@staff_member_required(login_url='/')
def delete_exam(request, id):
    exam = Exam.objects.get(id=id)
    exam.delete()
    return redirect('core:exam_crud')

core/templates/exam_crud.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% if request.user.is_authenticated and request.user.is_staff %}

{% block content %}
<div class="ftco-blocks-cover-1">
    <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
 <div class="site-section-cover overlay"
         style="background: linear-gradient(rgba(255,255,255,.4), rgba(255,255,255,.4)), url('{% static 'core/images/logo.jpeg' %}');
         background-attachment:fixed; background-position:center; height:100%;" >
        <div class="container">


            <div class="row align-items-center ">

                <div class="col-md-5 mt-5 pt-5">
                    <!--              <span class="text-cursive h5 text-red">Contact</span>-->
                    <h1 class="mb-3 font-weight-bold text-teal">لوحة الاسئله</h1>
                    <!--              <p><a href="index.html" class="text-white">Home</a> <span class="mx-3">/</span> <strong>Contact</strong></p>-->
                </div>

            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row ">
            <div class="col-12 text-center">
                <!--                <span class="text-cursive h5 text-red d-block">Packages You Like</span>-->
                <!--                <h2 class="text-white">لوحة الاسئله</h2>-->
            </div>
        </div>

        <div class="row mb-5">

            <div class="col-md-12 text-center">
                {% for m in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ m }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                <form method="post">{% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            {{ exam_form.question }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ exam_form.answer1 }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ exam_form.answer2 }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ exam_form.answer3 }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ exam_form.answer4 }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ exam_form.correct_answer }}
                        </div>
                        <button type="submit" class="text-center mx-auto btn-primary col-md-5 py-4 btn-custom-1 mb-3">اضافة سؤال</button>

                        <!--                    <div class="form-group">-->
                        <!--                        <label for="username" style="color:white;">اسم المستخدم</label>-->

                        <!--                        <input type="text" class="form-control" id="username" name="username">-->
                        <!--                    </div>-->
                        <!--                    <div class="form-group">-->
                        <!--                        <label for="exampleInputPassword1" style="color:white;">الرقم السري</label>-->
                        <!--                        <input name="password1" type="password" class="form-control" id="exampleInputPassword1">-->
                        <!--                    </div>-->
                        <!--                    <div class="form-group">-->
                        <!--                        <label for="exampleInputPassword2" style="color:white;">تاكيد الرقم السرى</label>-->
                        <!--                        <input name="password2" type="password" class="form-control" id="exampleInputPassword2">-->
                        <!--                    </div>-->

                        <!--                    <div class="form-group form-check">-->
                        <!--                        <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
                        <!--                        <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
                        <!--                    </div>-->
                    </div>
                </form>
            </div>
            <div class="row" style=" width:100%; background-color:white">

                <div class="table-responsive">
            <a class="text-center btn-block btn-primary py-4 btn-custom-1" href="{% url 'core:publish_questions' %}">انشر الاسئله</a>
                    <table class="table table-striped ">
                        <thead>
                        <tr>
                            <th scope="col" class="pl-4">#</th>
                            <th scope="col">السؤال</th>
                            <th scope="col">الاختيار الاول</th>
                            <th scope="col">الاختيار الثاني</th>
                            <th scope="col">الاختيار الثالث</th>
                            <th scope="col">الاختيار الرابع</th>
                            <th scope="col">الاختيار الصحيح</th>
                            <th scope="col">مسح</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for p in exam %}
                        <tr style="{% if not p.is_published %}background:rgba(255, 215, 51,.3)!important;{% endif %}">
                            <th scope="row" class="pl-4">{{ forloop.counter }}</th>
                            <td>{{ p.question}}</td>
                            <td>{{ p.answer1 }}</td>
                            <td>{{ p.answer2}}</td>
                            <td>{{ p.answer3}}</td>
                            <td>{{ p.answer4}}</td>
                            <td>{{ p.correct_answer}}</td>
                            <td><a href="{% url 'core:delete_exam' p.id %}"><i class="fas fa-trash-alt"></i></a></td>


                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>

                </div>


            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% endif %}

core/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="ftco-blocks-cover-1">
    <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
    <div class="site-section-cover overlay"
         style="background: linear-gradient(rgba(255,255,255,.4), rgba(255,255,255,.4)), url('{% static 'core/images/logo1.jpeg' %}');
         background-attachment:fixed; background-position:center; height:100%;" >
        <div class="container">
            <div class="row align-items-center ">
                <div class="col-md-6 mx-auto  ">
                    {% for m in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ m }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}

                {% if user.is_authenticated and request.user.is_staff %}
                    <a href="{% url 'core:staff_panel' %}" class="text-center btn-primary btn-block py-4 btn-custom-1">العوده للصفحه الرئيسيه</a>
                {% elif user.is_authenticated and not request.user.is_staff %}
                    <a href="{% url 'core:profile' %}" class="text-center btn-primary btn-block py-4 btn-custom-1">العوده للصفحه الشخصيه</a>
                {% else %}
                    <form method="post">{% csrf_token %}
                        <div class="form-group mb-5">
                            <input type="text" name="username" class="form-control" placeholder="اسم المستخدم">
                        </div>
                        <div class="form-group mt-5 mb-5 pt-5 ">
                            <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                                   placeholder="الرقم السري">
                        </div>
                        <button type="submit" class="text-center btn-primary btn-block py-4 btn-custom-1">تسجيل الدخول</button>
                    </form>
                </div>
                {% endif %}


                <!--                    <div class="col-md-5 mt-5 pt-5">-->
                <!--                        <span class="text-cursive h5 text-red">Welcome To Our Website</span>-->
                <!--                        <h1 class="mb-3 font-weight-bold text-teal">Packages</h1>-->
                <!--                        <p><a href="index.html" class="text-white">Home</a> <span class="mx-3">/</span>-->
                <!--                            <strong>Packages</strong></p>-->
                <!--                    </div>-->

            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/staff_panel.html
{% extends 'base.html' %}
{% load static %}
{% if user.is_authenticated and request.user.is_staff %}
{% block content %}

<div class="ftco-blocks-cover-1">
    <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
 <div class="site-section-cover overlay"
         style="background: linear-gradient(rgba(255,255,255,.4), rgba(255,255,255,.4)), url('{% static 'core/images/logo.jpeg' %}');
         background-attachment:fixed; background-position:center;" >
        <div class="container">

            <div class="row align-items-center ">

            <div class="col-md-5 mt-5 pt-5">
<!--              <span class="text-cursive h5 text-red">Contact</span>-->
              <h1 class="mb-3 font-weight-bold text-teal">لوح التحكم</h1>
<!--              <p><a href="index.html" class="text-white">Home</a> <span class="mx-3">/</span> <strong>Contact</strong></p>-->
            </div>

          </div>



        </div>
    </div>
</div>
<div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center">
<!--            <span class="text-cursive h5 text-red d-block">Packages You Like</span>-->
<!--            <h2 class="text-white">لوح التحكم</h2>-->
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="package text-center bg-white">
              <span class="img-wrap"><img src="{% static 'core/images/flaticon/svg/001-jigsaw.svg' %}" alt="Image" class="img-fluid"></span>
              <h3 class="text-teal">المخدومين</h3>
              <p>يمكنك من هنا اضافة مخدوم فى فصلك او مسحه او تعديل بياناته</p>
              <p><a href="{% url 'core:user_crud' %}"  class="text-center btn-primary btn-custom-1 mt-4 p-3">قم بالدخول</a></p>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="package text-center bg-white">
              <span class="img-wrap"><img src="{% static 'core/images/flaticon/svg/002-target.svg' %}" alt="Image" class="img-fluid"></span>
              <h3 class="text-success">الاسئله</h3>
              <p>يمكنك من هنا اضافة اسئله ومسحها</p>
              <p><a href="{% url 'core:exam_crud' %}" class="text-center btn-warning btn-custom-1 mt-4 p-3">قم بالدخول</a></p>
            </div>
          </div>
<!--          <div class="col-lg-4">-->
<!--            <div class="package text-center bg-white">-->
<!--              <span class="img-wrap"><img src="images/flaticon/svg/003-mission.svg" alt="Image" class="img-fluid"></span>-->
<!--              <h3 class="text-danger">Camping for Kids</h3>-->
<!--              <p>Lorem ipsum dolor sit amet. Consequatur aliquam, fuga maiores amet quo corporis distinctio soluta recusandae?</p>-->
<!--              <p><a href="#" class="btn btn-success btn-custom-1 mt-4">Learn More</a></p>-->
<!--            </div>-->
<!--          </div>-->
        </div>
      </div>
    </div>
{% endblock content %}
{% endif %}

core/templates/user_crud.html
{% extends 'base.html' %}
{% load static %}
{% if request.user.is_authenticated and request.user.is_staff %}

{% block content %}
<div class="ftco-blocks-cover-1">
    <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
 <div class="site-section-cover overlay"
         style="background: linear-gradient(rgba(255,255,255,.4), rgba(255,255,255,.4)), url('{% static 'core/images/logo.jpeg' %}');
         background-attachment:fixed; background-position:center; " >
        <div class="container">


            <div class="row align-items-center ">

                <div class="col-md-5 mt-5 pt-5">
                    <!--              <span class="text-cursive h5 text-red">Contact</span>-->
                    <h1 class="mb-3 font-weight-bold text-teal">لوحة المستخدمين</h1>
                    <!--              <p><a href="index.html" class="text-white">Home</a> <span class="mx-3">/</span> <strong>Contact</strong></p>-->
                </div>

            </div>
        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <!--                <span class="text-cursive h5 text-red d-block">Packages You Like</span>-->
                <!--                <h2 class="text-white">Our Packages</h2>-->
            </div>
        </div>
        <div class="row mb-5 ">
            <div class="col-md-6 text-center ">
                {% for m in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ m }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}

                <form method="post">{% csrf_token %}
                    <div class="form-group">
                        <label for="username" style="color:black;">اسم المستخدم</label>

                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1" style="color:black;">الرقم السري</label>
                        <input name="password1" type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword2" style="color:black; ">تاكيد الرقم السرى</label>
                        <input name="password2" type="password" class="form-control" id="exampleInputPassword2">
                    </div>

                    <!--                    <div class="form-group form-check">-->
                    <!--                        <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
                    <!--                        <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
                    <!--                    </div>-->
                    <button type="submit" class=" btn-primary py-4 btn-custom-1" style="padding:5%;; ">اضافة  مستخدم</button>
                </form>
            </div>
        </div>
        <div class="row" style="background-color:white">
            <a class="text-center btn-block btn-primary py-4 btn-custom-1" href="{% url 'core:export_data' %}">تصدير الى اكسل</a>
            <div class="table-responsive">


                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">اسم المستخدم</th>
                        <th scope="col">الدرجه</th>
                        <th scope="col">مسح</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for p in prof %}
                    <tr>
                        <th scope="row" >{{ forloop.counter }}</th>
                        <td>{{ p.user.username}}</td>
                        <td>{{ p.score }}</td>
                        <td><a href="{% url 'core:delete_user' p.user.id %}"><i class="fas fa-trash-alt"></i></a></td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>

            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% endif %}